<a href="https://colab.research.google.com/github/Gilmore-Floyd-R-Lozano/58013-Linear-Algebra/blob/main/Experiment_10.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np

X = np.array([
    [1,1,1],
    [3,-2,-1],
    [-1,4,2]
], dtype=float)
Y = np.array([
    [1],
    [4],
    [-3]
],dtype=float)
print(X)
print(X.shape)
print(Y)
print(Y.shape)


[[ 1.  1.  1.]
 [ 3. -2. -1.]
 [-1.  4.  2.]]
(3, 3)
[[ 1.]
 [ 4.]
 [-3.]]
(3, 1)


In [ ]:
#Coding Activity 10

import numpy as np
A0 = np.array([[30, 10, 120],
               [40, 20, 200],
               [50, 40, 360]])

A1 = np.array([[12500, 10, 120],
               [18000, 20, 200],
               [25700, 40, 360]])

A2 = np.array([[30, 12500, 120],
               [40, 18000, 200],
               [50, 25700, 360]])

A3 = np.array([[30, 10, 12500],
               [40, 20, 18000],
               [50, 40, 25700]])

A0det = np.linalg.det(A0)
A1det = np.linalg.det(A1)
A2det = np.linalg.det(A2)
A3det = np.linalg.det(A3)

flour = A1det/A0det
yeast = A2det/A0det
egg = A3det/A0det

print("Price of flour per sack:", round(flour,2))
print("Price of yeast per pack:", round(yeast,2))
print("Price of egg per piece:", round(egg,2))



Price of flour per sack: 330.0
Price of yeast per pack: 140.0
Price of egg per piece: 10.0
