<a href="https://colab.research.google.com/github/Gilmore-Floyd-R-Lozano/58013-Linear-Algebra/blob/main/Laboratory_9.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [56]:
import numpy as np
import matplotlib.pyplot as plt
%matplotlib inline

A = np.array([
    [1,4],
    [0,3]
])
np.linalg.det(A)


3.0000000000000004

In [55]:
## Now other mathematics classes would require you to solve this by hand,
## and that is great for practicing your memorization and coordination skills
## but in this class we aim for simplicity and speed so we'll use programming
## but it's completely fine if you want to try to solve this one by hand.

B = np.array([
    [1,3,5,6],
    [0,3,1,3],
    [3,1,8,2],
    [5,2,6,8]
])
np.linalg.det(B)


-235.0000000000002

In [58]:
# Associative Property
# (AB)C = A(BC)
import numpy as np
A = np.array([[10, 20, 30],
              [40, 50, 60],
              [70, 80, 90]])

B = np.array([[30, 20, 10],
              [60, 50, 40],
              [90, 80, 70]])

C = np.array([[20, 30, 10],
              [50, 60, 40],
              [80, 90, 70]])

AB_C = np.dot(np.dot(A, B), C)
A_BC = np.dot(A, np.dot(B, C))

equal = np.array_equal(A_BC, A_BC)

print("(AB)C:\n", AB_C)
print("\nA(BC):\n", A_BC)

print("\nResults are equal therefore:", equal)


(AB)C:
 [[ 504000  612000  396000]
 [1125000 1368000  882000]
 [1746000 2124000 1368000]]

A(BC):
 [[ 504000  612000  396000]
 [1125000 1368000  882000]
 [1746000 2124000 1368000]]

Results are equal therefore: True


In [59]:
# Distributive Property
# A(B+C) = AB + AC
A = np.array([[10, 10, 10],
              [10, 10, 10],
              [10, 10, 10]])

B = np.array([[1, 2, 3],
              [4, 5, 6],
              [7, 8, 9]])

C = np.array([[1, 1, 1],
              [1, 1, 1],
              [1, 1, 1]])

# A(B+C)
R1 = np.dot(A, np.add(B, C))
# AB + AC
R2 = np.add(np.dot(A, B), np.dot(A, C))

equal = np.array_equal(R1, R2)

print("A(B+C):")
print(R1)
print("\nAB + AC:")
print(R2)

print("\nResults are equal therefore:", equal)

A(B+C):
[[150 180 210]
 [150 180 210]
 [150 180 210]]

AB + AC:
[[150 180 210]
 [150 180 210]
 [150 180 210]]

Results are equal therefore: True


In [60]:
# Commutative Property
# AB != BA
A = np.array([[10, 20, 30],
              [40, 50, 60],
              [70, 80, 90]])

B = np.array([[30, 20, 10],
              [60, 50, 40],
              [90, 80, 70]])

AB = np.dot(A,B)
BA = np.dot(B,A)

print("AB:\n", AB)
print("\nBA:\n", BA)

print("\nAB ≠ BA")

AB:
 [[ 4200  3600  3000]
 [ 9600  8100  6600]
 [15000 12600 10200]]

BA:
 [[ 1800  2400  3000]
 [ 5400  6900  8400]
 [ 9000 11400 13800]]

AB ≠ BA


In [66]:
# Multiplicative Idendity Property
A = np.array([[1, 2, 3],
              [4, 5, 6],
              [7, 8, 9]])

I = np.eye(3,3)

AI = np.dot(A,I)

equal = np.array_equal(A, AI)

print(I,"\n")

print("A:\n",A)

print("\nAI:\n", AI)

print("\nA and AI are equal therefore:", equal)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]] 

A:
 [[1 2 3]
 [4 5 6]
 [7 8 9]]

AI:
 [[1. 2. 3.]
 [4. 5. 6.]
 [7. 8. 9.]]

A and AI are equal therefore: True


In [65]:
# Multiplicative Property of Zero
A = np.array([[1, 2, 3],
              [4, 5, 6],
              [7, 8, 9]])

O = np.zeros((3,3))
AO = np.dot(A,O)
equal = np.array_equal(O, AO)

print("O:\n",O,"\n")
print("AO:\n", AO)

print("O and AO are equal therefore:", equal)

O:
 [[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]] 

AO:
 [[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
O and AO are equal therefore: True


In [64]:
# Dimension Property
A = np.array([[1,2,3,4],
              [5,6,7,8],
              [9,10,11,12]])

B = np.array([[1,2,3],
              [4,5,6],
              [7,8,9],
              [10,11,12]])

AB = np.dot(A,B)

print("A:\n", A)
print("\nB:\n", B)
print("\nAB:\n", AB)
print("\nDimensions of AB:", np.shape(AB))

A:
 [[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]

B:
 [[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]

AB:
 [[ 70  80  90]
 [158 184 210]
 [246 288 330]]

Dimensions of AB: (3, 3)
