<a href="https://colab.research.google.com/github/Gilmore-Floyd-R-Lozano/58013-Linear-Algebra/blob/main/Python_Exercise_4.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [4]:
import numpy as np

A = np.array([[-0.4],
              [4.3],
              [-0.6]])
B = np.array([-0.2, 0.2, 1])
C = np.array([-0.2, 2.1, -1.5])

print("A:\n", A)
print("\nB:\n", B)
print("\nC:\n", C)

# Addition
sum = np.add(np.add(A,B),C)

# Subtraction
diff = np.subtract(np.subtract(A,B),C)

# Multiplication
prod = np.multiply(np.multiply(A,B),C)

# Division
quot = np.divide(np.divide(A,B),C)

print("\nAddition of Vectors A+B+C:\n", sum)
print("\nSubtraction of Vectors A-B-C:\n", diff)
print("\nMultiplication of Vectors ABC:\n", prod)
print("\nDivision of Vectors A/B/C:\n", quot)

A:
 [[-0.4]
 [ 4.3]
 [-0.6]]

B:
 [-0.2  0.2  1. ]

C:
 [-0.2  2.1 -1.5]

Addition of Vectors A+B+C:
 [[-0.8  1.9 -0.9]
 [ 3.9  6.6  3.8]
 [-1.   1.7 -1.1]]

Subtraction of Vectors A-B-C:
 [[ 0.  -2.7  0.1]
 [ 4.7  2.   4.8]
 [-0.2 -2.9 -0.1]]

Multiplication of Vectors ABC:
 [[-0.016 -0.168  0.6  ]
 [ 0.172  1.806 -6.45 ]
 [-0.024 -0.252  0.9  ]]

Division of Vectors A/B/C:
 [[-10.          -0.95238095   0.26666667]
 [107.5         10.23809524  -2.86666667]
 [-15.          -1.42857143   0.4       ]]
