<a href="https://colab.research.google.com/github/Gilmore-Floyd-R-Lozano/58013-Linear-Algebra/blob/main/Python_Exercise_3.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [15]:
# Vector Addition
import numpy as np

A = np.array([1,2,0])
B = np.array([3,1,-2])
C = np.array([0,0,1])

print(A+B+C)

print(np.add(A,np.add(B,C)))

print(np.sum(B))


[ 4  3 -1]
[ 4  3 -1]
2


In [4]:
# Vector Subtraction
print(np.subtract(A,B))

print(A-B)


[-2  1  2]
[-2  1  2]


In [7]:
# Vector Multiplication
print(np.multiply(A,B))

print(A*B)


[3 2 0]
[3 2 0]


In [13]:
# Vector Division
print(np.divide(A,B))

print(A/B)

C = np.array([3.9,1.8,7.7])
D = np.array([1,1,1])
C//D

print(np.array(A/B, dtype=int))


[ 0.33333333  2.         -0.        ]
[ 0.33333333  2.         -0.        ]
[0 2 0]
