<a href="https://colab.research.google.com/github/Gilmore-Floyd-R-Lozano/58013-Linear-Algebra/blob/main/Vector_Space_and_Operations.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [4]:
import numpy as np
A = np.array([4,3])
B = np.array([2, -5])

print("Vector A is", A)
print("Vector b is", B)



Vector A is [4 3]
Vector b is [ 2 -5]


In [24]:
##Shape of Matrix
import numpy as np

ball1 =np.array([1,2,3])
ball2 = np.array([0,1,-1])

print(ball1)
print(ball2)
ball = np.shape(ball1)
balls = np.shape(ball2)

print(ball+balls)




[1 2 3]
[ 0  1 -1]
(3, 3)


In [29]:
#Shape of Matrix
import numpy as np

ball1 =np.array([1,2,3])
ball2 = np.array([0,1,-1])
ball = np.vstack((ball1,ball2))

print(ball1.shape) # dimension of ball1
print(ball2.shape) # dimension of ball 2
print(ball.shape) # dimension of combined ball 1 and 2

print(np.shape(([ball1,ball2])))
print(ball)

#ball1 = np.array(([1],[2],[3])) column Vector

#ball2 = np.array([0,1,-1])
#print(ball1)




(3,)
(3,)
(2, 3)
(2, 3)
[[ 1  2  3]
 [ 0  1 -1]]


In [36]:
#Addition
import numpy as np

A = np.array([4,3])
B = np.array([2, -5])
R = np.add(A,B)


print(R)

[ 6 -2]


In [37]:
#Addition
import numpy as np

A = np.array([4,3])
B = np.array([2, -5])
R1 = np.subtract(A,B)
R2 = np.subtract(B,A)
print(R1)
print(R2)

[2 8]
[-2 -8]


In [39]:
#Scalar Product
s = np.array([2])
v = s*A
print(v)

[8 6]


In [48]:
#Multiplication
A = np.array([4,3])
B = np.array(([2], [-5]))
print(B*A)

[[  8   6]
 [-20 -15]]


In [50]:
#Dot Product
A = np.array([4,3])
B = np.array([2, -5])
print(np.dot(A,B))

-7


In [ ]:
#Cross Product
A = np.array([4,3])
B = np.array([2, -5])
print(np.cross(A,B))

In [75]:
#Property of Matrix
#Identity Matrix

c = np.eye(2,2)
print(c)

c = np.eye(3,3)
print("\n", c)

# Zero Matrix
c = np.zeros([5,5])
print("\n", c)

# Full Matrix
c = np.full((3,3),7)
print("\n",c)

#Transpose Matrix
c = np.transpose(A,axes = None)
print("\n", c)

#Empty Matrix
c = np.empty([2,2])
print("\n", c)

[[1. 0.]
 [0. 1.]]

 [[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]

 [[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]

 [[7 7 7]
 [7 7 7]
 [7 7 7]]

 [4 3]

 [[1. 0.]
 [0. 1.]]
